name: Python CI

on:
  push:
    branches:
      - main  # ou la branche que tu utilises
  pull_request:
    branches:
      - main  # ou la branche que tu utilises

jobs:
  pre_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Assure-toi de spécifier la version de Python souhaitée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances de ton projet
          pip install pre-commit  # Installe pre-commit
          pre-commit install  # Installe les hooks définis dans .pre-commit-config.yaml


      - name: Run pre-commit hooks
        run: |
          pre-commit run  # --all-files  # Exécute les hooks pré-commit sur tous les fichiers

      # - name: Run tests
      #   run: |
      #     pytest  # Ajoute ton framework de test ici si tu en as un
